name: reading_retention_tool
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.0
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: ^8.4.0
  firebase_analytics: ^5.0.2
  google_sign_in: ^4.0.7
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  file_picker: ^1.4.2
  firebase_storage: ^3.0.8
  provider: ^3.1.0+1
  cloud_functions: ^0.4.1+6
  share: ^0.6.3+5






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - Images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf