name: reading_retention_tool
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.2+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: ^8.4.0
  firebase_analytics: ^5.0.2
  google_sign_in: ^4.1.1
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  file_picker: ^1.4.2
  firebase_storage: ^3.0.8
  provider: ^4.0.4
  cloud_functions: ^0.4.1+6
  share: ^0.6.3+5
  flutter_local_notifications: ^1.1.3
  rxdart: ^0.23.1
  random_string: ^2.0.1
  get_it: ^3.1.0
  http: ^0.12.0+4
  flutter_svg: ^0.17.1
  flutter_image: ^3.0.0
  firebase_crashlytics: ^0.1.2+5
  encrypt: ^4.0.0









dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - Images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf